### ISSUE TITLE
[small improvement] add "Wall Dispense button, Panic" to "Program 5".

### ISSUE THREAD

**Issue by D4n2021** [the-paid-actor/dcs-dtc#1]
DCS .lua:

![grafik](https://user-images.githubusercontent.com/20766261/135755313-ea42ad1e-ce32-4137-ad14-359866b85c52.png)

Example suggestion on how to add it to DCS DTC:

![grafik](https://user-images.githubusercontent.com/20766261/135755385-fb6f0b8f-2671-4384-b6d1-520c487d7217.png)

[This obviously is so that us players can logically usefully dispense flares with 1 button and chaff with another button: "CHAFF/FLARE Dispense Button" and "Countermeasures Management Switch - Fwd" in DCS Keybindings. Thank you]

**Comment by the-paid-actor** [comment]
Players should know what each programs do independently of this app.
