### ISSUE TITLE
Hornet

### ISSUE THREAD

**Issue by Heater711** [the-paid-actor/dcs-dtc#12]
Please, add the support for the F/A-18C Hornet.

**Comment by HILOK** [comment]
pretty please 🙏😊

**Comment by p-louis** [comment]
I'm currently working on adding support for the hornet, you can track the progress on the pull request I created. 
Next features to add will likely be setting of radio channels and some of the misc stuff. Once I'm done with that, I'll add the countermeasure-settings.

**Comment by HILOK** [comment]
oh, great! thank you so much for doing this. 
i guess everyone's dream would be the ability of setting PP coordinates. AA radar presets (incl. AZ/EL) would also be high in ranking. don't know, if HSI/DATA options could also be preset? i am thinking of altitude warnings (baro & radar) and the AP BLIM option...
anyway, again thanks !!

**Comment by p-louis** [comment]
What do you mean by radar-presets? like bars, TWS/RWS, range and such? The other stuff is already implemented. The only thing on my list that is not yet done, besides some cleanup, is CMS-modes. I hope i will get around to implement that tomorrow.

**Comment by HILOK** [comment]
yes. as of now, the hornet's radar needs a lot of fine tuning to deliver its potential. option presets can be stored for every AA weapon by hitting the 'SET' PB. these option are mainly elev BARS, RANGE, AZIMUTH, HI/MED PRF, and also trackfile aging. there are even more options, but those are set by default. being able to load different presets for each AA weapon would be a big time saver.
thanks, cant wait to see & try the hornet DTC : )

**Comment by p-louis** [comment]
I'll look into the radar stuff and maybe implement it in the near future, i won't include it with this PR though.

**Comment by Heater711** [comment]
When Can we test the new DTC ?

**Comment by p-louis** [comment]
I have created a pre-release on my repository that has all the features besides countermeasures. Feel free to give it a shot.

**Comment by HILOK** [comment]
> I'll look into the radar stuff and maybe implement it in the near future, i won't include it with this PR though.

sure. i greatly appreciate all the work you put into this. thanks

**Comment by HILOK** [comment]
> I have created a pre-release on my repository that has all the features besides countermeasures. Feel free to give it a shot.

where can i find that?

**Comment by Heater711** [comment]
Actions

**Comment by Heater711** [comment]
> I have created a pre-release on my repository that has all the features besides countermeasures. Feel free to give it a shot.

We have an issue with the capture coords.

**Comment by p-louis** [comment]
Cheers, I think I found the issue you were having. You can check [this version](https://github.com/p-louis/dcs-dtc/releases/tag/3.3.0-RC4)  that should not have the issue
