### ISSUE TITLE
Crosshair captures wrong coordinates

### ISSUE THREAD

**Issue by Valk77** [the-paid-actor/dcs-dtc#14]
I notice an offset between the captured coordinates of the crosshair and the coordinates displayed on the F-10 map (see screenshot).
This is with version V3.1 although I already noticed it on previous versions.
I"m on a 1440p monitor if that would maybe make any difference.

![Capture  Coord](https://user-images.githubusercontent.com/76744561/149557908-79f7f971-ac96-400f-ab38-80954a9c49f3.PNG)

**Comment by digitalkibble** [comment]
yeah, i can confirm this as well.  also, it doesn't seem to matter if i change the in-game coordinates via (ALT+Y) into the correct format for the F16 or not.  i mean, i think this nifty program does that automatically for us, but yeah, my INS / GPS bombs were consistently hitting about 1nm to the east of where i mark.  anyway, this tool is awesome and hopefully this can get sorted as it's quite a nice QOL feature.

**Comment by the-paid-actor** [comment]
Old issue. I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels.
