### ISSUE TITLE
[FEATURE] FA18 Hornet A/A Attack Radar settings 

### ISSUE THREAD

**Issue by Wawar9** [the-paid-actor/dcs-dtc#19]
Hi, 

About the Hornet support, It would be very practical to be able to pre-set with the DTC the settings of the A/A ATTACK RADAR format. 

The idea is to set all the parameters in "RWS", then finaly press the "SET" button (OSB8) to ask the jet to memorise all those parameters as default settings if we change the master mode. 

So, in sequence, I suggest : 

- BAR settings (OSB1)
- Range (OSB6&7)
- Data Target History (OSB11 then OSB5)
- Azimuth degrees (OSB14)
- PRF (OSB16)
- SET to save the settings (OSB8)
- RWS/TWS (OSB20) (This one does not depend of the SET function, it is kept in memory anyway)
 
Thanks guys, awesome work. :-)

**Comment by bigronny** [comment]
This is by far our top feature request too

However, just to emphasize, given that there are 3 A-A ATTACK RADAR 'presets' available - one when selecting a Sidewinder from the HOTAS, one when selecting the Sparrow, and one when selecting an AMRAAM. 

Could you please allow the separate pre-setting of all of the settings OP mentioned, for each of these presets?

**Comment by the-paid-actor** [comment]
Old issue. I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels.
