### ISSUE TITLE
Feature request: allow blank steerpoints and altitudes

### ISSUE THREAD

**Issue by hbjonsson** [the-paid-actor/dcs-dtc#2]
Sometimes one might want to have steerpoints 1-5 on a connected line, but then create a disconnect between steerpoints 7-10, e.g. only show a line between 1-5 then 7-10. This is done by not entering any steerpoint values for steerpoint 6 in this case. V1.0 of this app does not allow this.

Also, It would be good to be able to not enter any altitude - which would then just result in a 0 being set for that waypoint.

**Comment by the-paid-actor** [comment]
Thats an interesting idea... will have to make the sequence number editable so you could skip waypoints.
I wonder if that would work with having the jet already loaded with waypoints... changing an existing waypoint to all zeros does not "remove" the waypoint from the jet, it sends it far away but keeps it connected.

**Comment by the-paid-actor** [comment]
Implemented on version 1.2.0 that by allowing you to add a "blank" waypoint setting latitude to all zeros... Then its skipped in the jet.
