### ISSUE TITLE
[FEATURE] Hornet - Allow setting of A/A waypoint (Bullseye)

### ISSUE THREAD

**Issue by bigronny** [the-paid-actor/dcs-dtc#20]
Again, fantastic work on this project

Could you please allow one of the waypoints to be assigned as the A/A (bullseye) waypoint in the DCS-DTC, and for it then to be pre-set in the jet

So sequence would be:
-Input all waypoints as normal
-Scroll to the designated A/A waypoint
-Box the A/A WP OSB

**Comment by the-paid-actor** [comment]
Old issue, already implemented. I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels.
