### ISSUE TITLE
[ISSUE] DCS-DTC 3.3.0 RC5 Hornet coordinates issue

### ISSUE THREAD

**Issue by Wawar9** [the-paid-actor/dcs-dtc#21]
Hi, 

Apparently, there is a bug with the waypoint capture/PP capture with the Hornet. 

When I try to capture a point with the Hornet, apparently DCS-DTC adds a "minute" on the coordinate. Problem that does not appear when I capture with the "F16 menu" of DCS-DTC. 

Hornet capture : 
![Bug DTC Hornet](https://user-images.githubusercontent.com/82789122/165178797-e7c52152-0806-4395-b327-7e021960ac3c.png)

Viper capture : 
![Bug DTC Viper](https://user-images.githubusercontent.com/82789122/165178783-e4875814-826b-44d7-9b2d-f4b744d9a81c.png)

**Comment by p-louis** [comment]
Judging from your screenshot, this looks like a rounding issue.
I have created a new pre-release that changes how the coordinate-formatting is handled [here](https://github.com/p-louis/dcs-dtc/releases/tag/3.3.0-RC6)

This should also remove such rounding issues.

**Comment by p-louis** [comment]
Fixed in RC6
