### ISSUE TITLE
[ISSUE] Hornet - Sequences

### ISSUE THREAD

**Issue by bigronny** [the-paid-actor/dcs-dtc#22]
DCS-DTC automatically adds waypoints to Seq 1 in the jet, when only waypoints are entered into the Seq 2 input box.

For example, let’s say you’ve entered a 7 waypoint flight plan into DCS-DTC, and you only set Seq 2 to be comprised of waypoints 5 & 6. Inside the jet, Seq 1 is still created and populated

**Comment by p-louis** [comment]
Do you have unchecked the Sequence 1 checkbox on the Sequences page? 
If you have it unchecked, Sequence 1 should only contain the waypoints set in the mission editor.
Also make sure to start out on Sequence 1. If you start on a different one, the settings will be offset accordingly
