### ISSUE TITLE
[FEATURE] FA18 Hornet AZ/EL IFF Auto Interrogation

### ISSUE THREAD

**Issue by Wawar9** [the-paid-actor/dcs-dtc#25]
Hi,

About the Hornet support, It would be nice to be able to activate or not the IFF Auto Interrogation in the AZ/EL Format. 

- AZ/EL Format
- AUTO INT (OSB16)

Thanks

**Comment by the-paid-actor** [comment]
Old issue. I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels.
