### ISSUE TITLE
[FEATURE] FA18 Hornet A/G fuze settings 

### ISSUE THREAD

**Issue by Wawar9** [the-paid-actor/dcs-dtc#26]
Hi,

About the Hornet support, It would be very practical if the current flow includes a fuze pre-set. 

For example with the current GPS weapons flow, even if the DTC enters the PP coordinates for us, we still have to manually enter the fuze setting for the bomb. (By default it is set to OFF).

The Fuze Setting is valid for all the weapons of the same name, no matter the hardpoint. So, if I have multiples GBU38 stations, I have to configure this setting only once. 

So, in sequence
- Store format
- Select ordnance
- EFUZ (OSB18)
- Select correct fuze (for example, INST is OSB18)

Thanks.

**Comment by the-paid-actor** [comment]
Old issue. I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels.
