### ISSUE TITLE
[FEATURE] FA18: Uploading Done

### ISSUE THREAD

**Issue by Heater711** [the-paid-actor/dcs-dtc#27]
I would be add a text message when the Uploader has been finished to load the datas on the aircraft.

"Data Loaded, Done !"

**Comment by VHellin** [comment]
Hi,
Do you need just a message like this ? 

![image](https://user-images.githubusercontent.com/21188226/202293935-cf92c6ef-39bd-47e2-8c79-1af89d0a396f.png)

**Comment by ags313** [comment]
Text message as in game, or window popping up?

**Comment by the-paid-actor** [comment]
Request already being tracked on Discord.
