### ISSUE TITLE
Feature: Keybinds

### ISSUE THREAD

**Issue by CBJamo** [the-paid-actor/dcs-dtc#3]
I play almost entirely in VR, so keybinds would be useful. The simplest would just be a way to hit the upload button from my macro pad. That way I could set up my DTC before hopping into VR, then once my jet is powered up I just hit the upload keybind and don't have to mess with a virtual desktop or the steam overlay.

Another use case would be to streamline capturing waypoints. So keybinds for add, start/stop capture, and save. That way you don't need to tab out from DCS while capturing waypoints.

**Comment by the-paid-actor** [comment]
Old issue. I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels.
