### ISSUE TITLE
[REQUEST] Add VRP / VIP WP and information addition to DED Upload

### ISSUE THREAD

**Issue by alcmann** [the-paid-actor/dcs-dtc#31]
Requesting addition of VRP / VIP WP and information addition to DED Upload.

Thoughts are under Waypoint tab could add a checkbox for VIP / VRP to make that particular WP either, then the addition of Range/ALT/Bearing for each databox on the Waypoint.

For OA1/OA2 again check box for each Waypoint popup when entered, Checking the "Offsets enabled" box would allow data entry for the waypoint   RANGE/BEARING/ALTITUDE

**Comment by Heater711** [comment]
nice addiction

**Comment by alcmann** [comment]
Reached out to Kikaku for this POP up delivery program with DED Data.  If he could work out an export feature to flow into DTC or  maybe DTC software could be built to incorporate the planner all together like the liaison with "theway" something could be reached. 

Thanks again.
Great tool here
https://www.digitalcombatsimulator.com/en/files/3325532/

**Comment by alcmann** [comment]
Any thoughts on this ?? or luck reaching out to Kikaku ?

**Comment by alcmann** [comment]
Had spoken with Kikaku, Have the possibility for his program to export in .JSON.   Could be intigrated into DTC data import.

**Comment by rglasinovic** [comment]
Nice add. Any news?

**Comment by p-louis** [comment]
Hey, 
Given that I'm not very familiar with the Viper, could you detail out the changes this would require?

Having Kikaku's tool export JSON data for use with DTC should be rather simple to do. However, if this additional feature requires any changes to the data-model -- which it sounds like it would -- He could only get started once the feature is implemented on here.

Another issue I see with this is that the model may change again at some point to unify the way coordinates are handled between different A/Cs implementations.

**Comment by the-paid-actor** [comment]
Old issue, partially implemented. I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels.
