### ISSUE TITLE
[REQUEST] F/A-18C: Precise Waypoint Entry

### ISSUE THREAD

**Issue by Gosling616** [the-paid-actor/dcs-dtc#33]
Often waypoint are entered having Boxed the "Precise" OSB19. But waypoints currently can only be entered with Two decimal places to the minutes. Please could we have a "Precise" checkbox to allow Waypoints to be defined with 4 decimal place to the minutes.

**Comment by ghosty141** [comment]
@p-louis any progress on this? This would be a great addition!

**Comment by p-louis** [comment]
Can't say there is, I haven't really done any development work on this project in a while because, well, time...
But I'd be happy to accept any PRs that introduce this.

**Comment by the-paid-actor** [comment]
Feature request already tracked on Discord.
