### ISSUE TITLE
Trojan warning?

### ISSUE THREAD

**Issue by guirk** [the-paid-actor/dcs-dtc#38]
Chrome and Windows Defender just popped off

**Comment by amn2be** [comment]
> 

Same here cannot download.

**Comment by Gosling616** [comment]
Same here - Message left for you on Discord

**Comment by p-louis** [comment]
I've submitted the RC12-file to Microsoft to get it whitelisted. This may take a few days. I'll leave the issue open for now and update it once the review is done.

**Comment by p-louis** [comment]
Microsoft has removed the file from it's malware definitions.
Please follow the steps below to clear cached detections and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

**Comment by Couby** [comment]
Hi,

This is back the case with RC13 😅 .
