### ISSUE TITLE
[REQUEST] Add Waypoint windows - find-as-you-type search

### ISSUE THREAD

**Issue by rglasinovic** [the-paid-actor/dcs-dtc#40]
[REQUEST] Add Waypoint windows - find-as-you-type search
Hi.
It would be great to have the ability to find and add waypoint to the route with find as you type search. This is very helpfull when you have a big database of coded waypoints. Our community has hundreds of coded DPIs so, it would be great to find each one while typeing its code. Currently the seach works with the first typed characters; if you type anothed one, the search is reseted.
Thanks, and please keep working on this. This tool es really powerfull.

**Comment by the-paid-actor** [comment]
I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels. Please request it there.
