### ISSUE TITLE
F18 ISSUE

### ISSUE THREAD

**Issue by Danguard63** [the-paid-actor/dcs-dtc#41]
For any terrain i have an issue from wp4 to next. When i try to upload to jet until wp3 no problems al all from wp4 th software upload empty coordinates and i have an ERROR blinking in the avionic. With F16 no problem at all.

**Comment by p-louis** [comment]
Try increasing the `CommandDelayMs` value in the dtc-settings.json this usually fixes the data-input issues

**Comment by Danguard63** [comment]
Ok i'll try what value should i use? By the way i can't find your discord profile, can you rewhrite right there?

**Comment by p-louis** [comment]
Other people with similar issues have reported that 500 worked reliably for them, so I'd start there and maybe try out different values closer to the original 200 until you find something that works reliably for you.

**Comment by Danguard63** [comment]
Just sent you friendship request on Discord i'm Danguard#7029

**Comment by Danguard63** [comment]
In any case 500 worked for me, is it milliseconds?

**Comment by Danguard63** [comment]
Sorry i made a new mission with a simple flight plan and i had the error problem for point 5 for altitude. I tried also with 1000 ms with the same problem. I would send you the 7z file with track, the mission and the json file.
[danguard_test.zip](https://github.com/the-paid-actor/dcs-dtc/files/9354822/danguard_test.zip)

**Comment by p-louis** [comment]
The issue you're running into is that the hornet doesn't accept waypoint altitudes above 25000ft. This leads to an error on entry of WP3 which breaks the input sequence for the following waypoints.

I will include a check for this in the future, but for now I can just ask you to stay within the A/Cs limits :)
