### ISSUE TITLE
DTC number station is different with inflight station

### ISSUE THREAD

**Issue by serginio050** [the-paid-actor/dcs-dtc#43]
Hello p-Louis
I'm running the 3.3.0-RC12 version and i noticed this difference.

In DTC my preplanned settings are:
station2= coord target1
station3= coord target2
station7= coord target3
station8= coord target4

In flight dropped bomb of:
station2 touch target4
station3 touch target3
station7 touch target1
station8 touch target2

Thanks for your reading. And i hope that is help this great program being better.

**Comment by serginio050** [comment]
?

**Comment by the-paid-actor** [comment]
Old issue, probably already fixed. I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels.
