### ISSUE TITLE
Feature Request: Plugin

### ISSUE THREAD

**Issue by dmeador** [the-paid-actor/dcs-dtc#44]
Hi Guys, great work on this DTC!  I'd like to contribute some additions.  I am thinking something like a plug-in framework which would allow custom import of data from clipboard or file/xml/json/whatever into the DTC data pages.  I have currently modded to do this for pulling in data from my squadron waypoint data which works, however it's not sustainable to maintain a fork and constantly back port.  I'd like to add something generic plugin feature for to the DCS-DTC so that the importer / plugin will get carried along with with the code base and feature updates.  Do you have any interest in incorporating a plugin feature or something like it?

**Comment by p-louis** [comment]
Hey!
If it's just about the load/save functionality, the simplest way would be to produce a fitting JSON structure and store it in the clipboard. I don't think either of us has this on their wish-list right now or the time to develop a full fledged plugin system.

You're welcome however to create a merge request with that.

**Comment by the-paid-actor** [comment]
Old issue. I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels.
