### ISSUE TITLE
F/A-18C: PrePlanned JDAM using incorrect Lat/Lon format

### ISSUE THREAD

**Issue by martinco** [the-paid-actor/dcs-dtc#46]
Love the work

When creating a PrePlanned Lat / Lon, DCS_DTC attempts to upload to the 18 using Degrees Decimal Minutes to 4 decimal places where it should be using Degrees Minutes Seconds to 2 decimal places

This can be shown by creating a PP position with a decimal component >= 60 (such as this building east of Sharjah)

```
N  25 18.7540 
E 055 34.8400
141ft
```

Upon uploading to the 18, it attempts to enter as:

* Lat: 25 18 75 _enter_ 40 _enter_
* This causes an error as 75 is not a valid number of seconds (and 84 on Lon)

The location should be entered in DMS as:

```
N  25 18 45.24
E 055 34 50.40
141ft
```

Thanks,
Martin

**Comment by p-louis** [comment]
Cheers,
Just to clarify: Is this an issue with validating user input or does the coordinate capture produce these malformed coordinates?

**Comment by martinco** [comment]
Ohhhhh, okay - it's a User Input / UX issue

Coordinate Capture is capturing the correct (DMS) value, but the application is presenting it as a DDM value (incorrect)

See attached (the mouse cursor was inside the crosshairs) showing degrees decimal minutes in the top bar

![image](https://user-images.githubusercontent.com/250888/198064372-91bcae75-3626-4e2f-84af-a82b7c051207.png)

This leads to an ambiguity from a user entry perspective to input degrees decimal minutes to 4 decimal places which is not really what it's after.

Interpreting the application value as presented would be ~800m away from the intended target!

```
Target (real DMS)    App Display (DDM)    Target (real DDM) 
N 25°18'45.24"       N 25°18.4524'        N 25°18.7540'
E 55°34'50.38"       E 55°34.5038'        E 55°34.8397'
```

**Solution**

Update "Set Pre Planned Position" formatting dialog to show DMS correctly, then all would work as expected

```
[NS] [Degrees]° [Minutes]' [Seconds].[XX]
```


Hope that clears it up!
Thank you

**Comment by p-louis** [comment]
I understand! Thanks for the detailed description of the issue :)
