### ISSUE TITLE
Multimonitor Support

### ISSUE THREAD

**Issue by Konstantinos-the-Great** [the-paid-actor/dcs-dtc#5]
Currently the Cross hair for waypoint capture appears only on the main display.
On my setup the map is shown on another display where I cannot move the crosshair.
It would be of great help if I could move the crosshair (Win + Arrow) in more than one positions.
Many thanx your mode is great.

**Comment by Konstantinos-the-Great** [comment]
The option for a white crosshair would be helpful as well against the black background of the main (non dcs) monitor.

**Comment by the-paid-actor** [comment]
Old issue. I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels.

**Comment by Konstantinos-the-Great** [comment]
Thanx
