### ISSUE TITLE
No FA/18 Preset / Option on DTC.exe

### ISSUE THREAD

**Issue by odskee** [the-paid-actor/dcs-dtc#51]
Have downloaded the v3.2.0 release, copied & edited scrips but when launching dtc.exe, the only available option is F16 - there's no FA18 preset option showing (or AH-64).  What do I need to do to enable this / how do you use this for the FA18?

**Comment by Sirtz** [comment]
Same problem just with AH-64. I would guess this is a DCS 2.8 change.

**Comment by p-louis** [comment]
Cheers @odskee, @Sirtz ,

The reason for this is that 3.2.0 does not contain either of those additions, however version 3.3.0 will contain these.
Right now it's not quite ready to drop the new release, as PR #52 isn't merged yet and I want to do some more testing before doing so.

For the moment, you can find a release that supports the F/A-18C on my [fork](https://github.com/p-louis/dcs-dtc/releases/tag/3.3.0-RC13) and a version that supports the AH-64 on @PieterL1976 s [fork](https://github.com/PieterL1976/dcs-dtc/releases/tag/v0.0.4-alpha)
