### ISSUE TITLE
DCS-DTC-3.3.0-RC13  F/A-18C PrePlanned does not work

### ISSUE THREAD

**Issue by PVI-Bat** [the-paid-actor/dcs-dtc#53]
When I load the PP coordinates, starting from the HSI on the left MFD, the DCS-DTC stops on the storages page.
Also to another friend it does the same. 
Instead for another friend it works regularly.
We run DCS-TDC in the same way, with the same file that we import.

**Comment by the-paid-actor** [comment]
Old issue. I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels.
