### ISSUE TITLE
[Issue] Coordinate entry error on waypoints F-18

### ISSUE THREAD

**Issue by Wamwod** [the-paid-actor/dcs-dtc#55]
![image](https://user-images.githubusercontent.com/71331178/211421733-39977f75-4dce-46f0-9168-a9f1cdc33207.png)
The Image here shows the format which is what the LAT/LNG on the DTC reads as DDM or decimal, but actually takes the seconds format from the input on the F-10 map.

**Comment by Wamwod** [comment]
The issue is under .\dcs-dtc\UI\Aircrafts\FA18\WaypointEdit.cs > btnCapture_Click 
Line 217 should be a new class for DM.DD instead of DM.DDD or DMS.

**Comment by Tronald** [comment]
FYI,

This mod is already using `CoordinateSharp`. I would suggest just allowing it to handle parsing for you guys. This would allow a lot more flexibility when parsing, but you can also restrict to specific formats like in this example:

https://dotnetfiddle.net/ENgp9Y

I can give tips on this if needed.

**Comment by p-louis** [comment]
Yeah CoordinateSharp was introduced with the AH-64, it is yet to be used for any of the other airframes though.
Besides that, this is merely a display issue, on the form/table not an issue with coordinate formatting.

**Comment by the-paid-actor** [comment]
Fixed on latest version. For other issues, please join Discord as I don't track stuff here.
