### ISSUE TITLE
FA-18C Pre-Planned Weapon Coordinates

### ISSUE THREAD

**Issue by jspencer46** [the-paid-actor/dcs-dtc#59]
Perhaps NOT an issue with the program, but with the documentation? I can not get DCS DCT to properly load the PP weapon coordinates, for JSOW for example, to the aircraft. Coord entry seems correct (see screenshot) and I see the UFC buttons being pressed. Nevertheless the weapon stores page shows no PP coordinates for the weapons. DCS OB 2.8.2.35759. Win 11. DCS DCT 3.3 RC 13.

![Screenshot_20230215_080352](https://user-images.githubusercontent.com/33643392/219035256-50fd6c14-ea03-4b58-9906-63cff2a65c22.png)

**Comment by the-paid-actor** [comment]
There were some bugs (including with JSOW-C) that were fixed already. If not please report on Discord.
