### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by Couby** [the-paid-actor/dcs-dtc#60]
Hi,
Would it be possible to explain a beginer how to compile ? From vs code install to successfull build, if possible 😊

**Comment by nerijustt** [comment]
I'm also interested :)

**Comment by ghosty141** [comment]
You need Visual Studio, not just VS Code. From there it's *relatively* simple, basically just click "Build -> Build Solution". I'll probably make an issue that has a link to download the binaries (.exe) since the author seems inactive.

**Comment by the-paid-actor** [comment]
I am active now, but don't track stuff here, only on Discord.
