### ISSUE TITLE
Feature Request. Work with Lazy MDC's Cardbuilder for DTC Files

### ISSUE THREAD

**Issue by alcmann** [the-paid-actor/dcs-dtc#62]
Greetings.  

As online play and working multiple DTC cards on a multiplayer server would love the ability to load the exported .json data into LazyMDC's cardbuilder.  That way would could use a kneeboard to reference for all the DTC data and waypoints etc.

Export / Import feature compile between the two. Filing a similar feature request on the corresponding git ! hopefully some great DCS Synergy 
https://github.com/martinco/LazyMDC

**Comment by the-paid-actor** [comment]
I'm concentrating all feature requests/issues on Discord to not have to monitor multiple channels. Please request it there.
