### ISSUE TITLE
Installer only looks for SG\DCS and DCS.OpenBeta

### ISSUE THREAD

**Issue by OR-WS** [the-paid-actor/dcs-dtc#65]
The installer of v4 seems hardcoded to install in either SG\DCS or SG\DCS.OpenBeta, it does not look any further so unless you have a single installation of DCS using ED's defaults, you can't install it. E.g. I would need DCS DTC to install in SG\DCS.Client_1.

**Comment by OR-WS** [comment]
Can we perhaps at least get acknowledgement that this is considered a point for improvement please?

**Comment by the-paid-actor** [comment]
Sorry for the long time without answer, but as I said in the ED forum I only actively track feature requests or bugs in Discord. I didn't had time yet to clean all the issues here on github and close the section.

**Comment by the-paid-actor** [comment]
@OR-WS
On your Documents/DCS-DTC folder you have a file dtc-settings.json. Replace its contents with this:

```
{
	"TCPSendPort": 43001,
	"UDPReceivePort": 43000,
	"CommandDelayMs": 200,
	"AlwaysOnTop": true,
	"LuaInstallFolderStable": null,
	"LuaInstallStable": "False",
	"LuaInstallFolderOpenBeta": "C:\\Users\\<whatever username>\\Saved Games\\DCS.Client_1",
	"LuaInstallOpenBeta": "True"
}
```

Replace <whatever username> with your username, or even replace the whole path. Make sure to put double backslashes.
This should be enough to solve it for you. If not, please come to Discord and I can give you real-time support.

**Comment by OR-WS** [comment]
I didn't know about primarily using Discord for bug tracking as I don't visit ED.ru when I don't have to but I guess that one's on me. Thanks for getting back to it!
