### ISSUE TITLE
Radios three decimal places

### ISSUE THREAD

**Issue by irishluck494** [the-paid-actor/dcs-dtc#66]
Hello, would be awesome for our multiplayer group if we were able to set radio frequencies to the thousandths place, as lots of our freq's are using XXX.XX5 format. Thanks!

**Comment by the-paid-actor** [comment]
I don't know if you are referring to the Hornet or Viper? If its the Hornet, its been fixed already. If not, please join Discord as I don't track things on Github.

**Comment by irishluck494** [comment]
Yeah the very best patch had this haha, much appreciated!




On Monday, June 26, 2023, 7:42 PM, the-paid-actor ***@***.***> wrote:




Closed #66 as completed.
