### ISSUE TITLE
[Suggestion] Ability to set bars and azimuth settings for A/A weapons on the F-18

### ISSUE THREAD

**Issue by OfficialDSplayer** [the-paid-actor/dcs-dtc#67]
On the F-18, by default their are set A/A radar bars and azimuth presets for the weapons (SW, Sparrow, AMRAAM) but you can override this by using the SET button in RWS. It would be cool to have this as an option within this program similar to the CM programs.

**Comment by the-paid-actor** [comment]
Check V7 published today
