### ISSUE TITLE
[Suggestion] Ability to enumerate with period in F-15E

### ISSUE THREAD

**Issue by Niroi** [the-paid-actor/dcs-dtc#68]
The strike eagle has the ability to set target points with the dot as in 3.1, 3.2, 3.3 etc. I think it would be neat if this function could be added. Maybe while setting up a regular waypoint e.g. 4 there could be an optional checkmark for adding a target point to the current one which would then enumerate starting with 4.1 and continuing.

**Comment by the-paid-actor** [comment]
I don't track issues here. Already suggested on Discord.
