### ISSUE TITLE
[Sugestion] Add compatibility with A-10C II

### ISSUE THREAD

**Issue by JesuisOriginal** [the-paid-actor/dcs-dtc#70]
Add the hability to add waypoints and configure CBUs and JDAMs from the DCS DTC, as well as Radio.

**Comment by VRabadan** [comment]
Yes please! 
This would be awesome to make flight plans for the A10CII!!!!

**Comment by 32ndAirCombatWings** [comment]
Bump

**Comment by 32ndAirCombatWings** [comment]
BUMP AGAIN

**Comment by the-paid-actor** [comment]
I don't track issues here, there is already a request for it on Discord
