### ISSUE TITLE
5.04 update F-15 MFD selects the wrong buttons

### ISSUE THREAD

**Issue by CrazyPotatoes** [the-paid-actor/dcs-dtc#71]
The MFD M pages have different functionality now and uploading does not cycle the buttons on the correct M page.

**Comment by Wawar9** [comment]
Had the same issue. Manual reinstall of the main files AND the script files in saved games fixed the issue for me.

**Comment by CrazyPotatoes** [comment]
I reinstalled it the same, the problem persists. I don't know what is different. I went through every file and it's completely updated.
