### ISSUE TITLE
[F-16] Blank steerpoints lead to line drawn to 0.0

### ISSUE THREAD

**Issue by drsoran** [the-paid-actor/dcs-dtc#75]
I discovered a strange behavior since one of the last updates. I always used the "blank steerpoints" in the Viper to draw independent boxes on the HSD as a workaround for the missing HSD lines. But now the empty steerpoints are not skipped anymore and a line is drawn to the 0,0 coordinate on the HSD. Could also be a DCS update that caused this. I think once the coordinate is entered into the STPs during upload it is drawn now. Even if it is still 0.0.

The empty coordinates in the JSON are set to `IsCoordinateBlank": true`. I suppose that these coordinates need really to be skipped now when uploading.

I attached my DTC json and a screenshot.

[palmyra.dcs_dtc.json.txt](https://github.com/the-paid-actor/dcs-dtc/files/12447657/palmyra.dcs_dtc.json.txt)

![image](https://github.com/the-paid-actor/dcs-dtc/assets/897403/2d8cc373-2885-4851-994f-f287ecaa573c)

Thanks for your great work and the great tool!

**Comment by the-paid-actor** [comment]
I dont think ED fixed their side, I reported this before but they said "correct as is"
Anyway, check V7 published today, it allows you to skip waypoints.
