### ISSUE TITLE
UI issues immediately after entering F-16 waypoint elevation greater than 25000

### ISSUE THREAD

**Issue by wonkotron** [the-paid-actor/dcs-dtc#79]
After entering a F-16 waypoint elevation greater than 25000, a **recoverable** UI issue can be observed.

**Versions**
- 5.3.3
- 5.3.0 (workaround not tested)

**Steps to Reproduce**
1. Open application
2. Select F-16
3. Load saved profile
4. Add a new waypoint or load existing
5. Enter an elevation value greater than 25000
6. Observe an inability to Save, Cancel, or change to a different screen within the open profile (i.e. Upload to Jet, Load/Save, etc.)

**Recovery Workaround**
Click F-16C Presets or Home to restore the application to a working state.

**Comment by the-paid-actor** [comment]
Check V7 published today, otherwise please report on Discord
