### ISSUE TITLE
Minimze button

### ISSUE THREAD

**Issue by nevara** [the-paid-actor/dcs-dtc#8]
The DTC needs a minimize button. In VR, the DTC window overlaps DCS which results in clicks in DCS taking me outside of DCS. 

If the DTC could be minimized, that would eliminate the issue. Also, "Upload to JET" keybinds would be great.
Also, I would prefer not to have the custom chrome override the Windows look and feel. Keep it minimalistic.

**Comment by p-louis** [comment]
There is a minimize button on the application, so this issue might have needed to be closed earlier. However I will do so now as it's no longer current.
