### ISSUE TITLE
[Suggestion] Sound at the end of upload.

### ISSUE THREAD

**Issue by Amarok73** [the-paid-actor/dcs-dtc#83]
Hello,

Would it be possible to add the feature that the sound would be played at the end of data cartridge upload? Prefferably in some typical sound file located in the application directory so it could be "moddable".

**Comment by alcmann** [comment]
This would be a nice feature.  I have thought about this in the past if it played a type of "chime" or "ding" or whatever was used as an optional sound file, would be a great optional feature.

**Comment by the-paid-actor** [comment]
Can't play sounds from within DCS, but V7 published today has a visual indicator
