### ISSUE TITLE
F16 Waypoint Capture Marker Off-Center

### ISSUE THREAD

**Issue by MowgliViper** [the-paid-actor/dcs-dtc#86]
Running dual screens, the primary is 2560x1440, and the secondary is 1920x1200 (where I run extra tools for DCS like DTC). When running DTC on the secondary screen and pressing waypoint capture, the aiming cursor of the capture is off center about 45 degrees top-left. The issue is resolved when repeating the process but having DTC open on the same screen as DCS.

It occurred on 5.3.4 and previous 5.3.x versions.

**Versions tested**
5.3.x

**Running of the same screen:**
![9d978d8dfffd5d57b2ea9a18810b53a4](https://github.com/the-paid-actor/dcs-dtc/assets/155012573/0f17fc71-a511-400e-829f-920775762ef4)

**Running of two different screens:**
![f1e5da36f93bba6a744a7880225615f1](https://github.com/the-paid-actor/dcs-dtc/assets/155012573/bd26a3ad-d2ee-459c-8252-a8de3fe4b9b2)

**Comment by the-paid-actor** [comment]
Check V7 published today
