### ISSUE TITLE
2.7.8.16140 update..

### ISSUE THREAD

**Issue by Colmill0** [the-paid-actor/dcs-dtc#9]
Hi
Since last update, It is not working properly. When loading waypoints for example, it is seen that the keys are actuated but not in a correct order.
The same thing happens with the frequencies, the rest I have not tested.

Thank you for your work, I hope you can solve this problem.

https://user-images.githubusercontent.com/85252541/142880201-f1119f26-130a-4dcc-bf1f-43d3d56851d3.mp4

**Comment by melch53** [comment]
In the dtc-settings.json increase "CommandDelayMs" from 100 to 200

**Comment by Colmill0** [comment]
Perfect!
Thanks

**Comment by the-paid-actor** [comment]
Also fixed on latest release.
